name: jupyter-aj
version: 0.0.3
summary: Testsnap for Jupyter
title: Jupyter AJ.
description: 'Simple Webbased Editor
'
icon: snap/icon/logo.png
base: core20
confinement: strict
grade: stable

apps:
  jupyter:
    command: bin/jupyter-notebook --allow-root --no-browser --config /snap/jupyter-aj/current/jupyter_notebook_config.py
    daemon: simple
    plugs:
      - network-bind
      - network-status
      - network-observe
      - serial-port
      - active-solution

  jupyterlab:
    command: jupyterlab
    daemon: simple
    plugs:
      - network-bind
      - network-status
      - network-observe
      - serial-port
      - active-solution

parts:
  jupyter:
    plugin: python
    source: .
    python-packages:
      - jupyter
      - ctrlx-datalayer
      - ctrlx-fbs
      - numpy
      - jupyterlab
      - matplotlib
      - wheel
    build-packages:
      - libzmq3-dev
      - libsystemd-dev

  deb:
    plugin: dump
    source: https://github.com/boschrexroth/ctrlx-automation-sdk/releases/download/1.14.0/ctrlx-datalayer-1.7.13.deb

  configs:
    source: ./configs
    plugin: dump
    organize:
      'package-assets/*': package-assets/${SNAPCRAFT_PROJECT_NAME}/

  lab:
    source: ./lab
    plugin: dump

slots:
  package-assets:
    interface: content
    content: package-assets
    source:
      read:
      - $SNAP/package-assets/${SNAPCRAFT_PROJECT_NAME}

plugs:
  active-solution:
    interface: content
    content: solutions
    target: $SNAP_COMMON/solutions
